openapi: "3.0.3"
info:
  title: "AstonIntensive31HomeWorks API"
  description: "AstonIntensive31HomeWorks API"
  version: "1.0.0"
servers:
  - url: "https://AstonIntensive31HomeWorks"
tags:
  - name: "FindTeachers controller"
    description: "Service for find Teachers"
paths:
  /teachers/{course-name}:
    get:
      summary: "Find teachers by course"
      description: ""
      operationId: ""
      parameters:
        - name: "course-name"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "202":
          description: "Teachers found"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TeacherResponse"
        "404":
          description: "Cannot find any teachers"
components:
  schemas:
    TeacherDto:
      type: "object"
      properties:
        isTeacher:
          type: "string"
        firstName:
          type: "string"
        LastName:
          type: "string"
    TeacherResponse:
      type: "object"
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/TeacherDto"